name = "MacaulayLab"
uuid = "f2186eeb-a3bb-4592-933c-7229474ceaba"
authors = ["Benoît Legat <benoit.legat@gmail.com>"]
version = "0.1.0"

[deps]
MATLAB = "10e44e05-a98a-55b3-a45b-ba969058deb6"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"

[compat]
MATLAB = "0.8"
MultivariatePolynomials = "0.5"
SemialgebraicSets = "0.3"
julia = "1.6"
